### ISSUE TITLE
Websocket keeps disconnecting: Error Message

### ISSUE THREAD

**Issue by Chroni69** [JustYuuto/deezer-discord-rpc#11]
Hey,

the Websocket keeps disconnecting between every ~30 to 60 minutes and the error message also comes out on top of a fullscreen application. Manually reconnecting always works immidiately again so I think it would be great to add an auto-reconnect if connection gets lost and ideally the error message only appears after X failed retries or just remove it completely.

Thanks a lot for your work!

**Comment by JustYuuto** [comment]
Hi, thanks for reporting the bug, I am working on it.
