### ISSUE TITLE
Listening to lower priority than games

### ISSUE THREAD

**Issue by Zalk0** [JustYuuto/deezer-discord-rpc#15]
It may be on Discord side but when I select "Use listening to instead of playing" I need to not have any game launched otherwise it doesn't show and I see my game.

Playing :
![image](https://github.com/JustYuuto/deezer-discord-rpc/assets/88582103/652ecd2b-a8a7-4052-8a7f-2c447cbe4fef)
Yeah we have the two "games" side by side and the RPC takes priority so Deezer.

Listening :
Game open :
![image](https://github.com/JustYuuto/deezer-discord-rpc/assets/88582103/66d7eebc-0edb-45fc-9f05-320d2f7a32e0)
Game closed :
![image](https://github.com/JustYuuto/deezer-discord-rpc/assets/88582103/f7b01a5c-b07d-4f67-8df0-51a447087efd)
Here Deezer is not counted as an RPC because of the weird websocket thing (I don't know exactly what you do) so they have same priority and it seems like the first "game" launched takes priority.

It's kinda annoying as it's inconsistent. I don't know if you (or someone else) experienced the same issue.
I'm not sure you can do anything about it (probably not) but adding a disclaimer would be nice.

**Comment by Chroni69** [comment]
This is exactly what is supposed to happen. Most people want their games to have the priority over Deezer, which the "Listening to" option does (I'm sure that's why it's called "way better"). And if you don't want that to happen then use the "Playing" option and start Deezer first.

**Comment by Zalk0** [comment]
Yeah I thought so thanks for explaining to me.
