### ISSUE TITLE
Sometimes the song timer goes to zero before the end of the song being played

### ISSUE THREAD

**Issue by clovislfbv** [JustYuuto/deezer-discord-rpc#2]
Hi,
I love your project. I now use it very regularly and I noticed that sometimes, when rewinding a music or even just letting this deezer play the music, the timer displayed on discord reaches zero far before the music ends. I don't think this is a major bug but I wanted to point it out to you just in case.
![image](https://user-images.githubusercontent.com/79811391/229309287-44bd679e-02f0-4f88-8cef-a6a4d5d68340.png)
![image](https://user-images.githubusercontent.com/79811391/229309317-f3099f26-3153-488c-baed-b3c1e8350bb2.png)

**Comment by JustYuuto** [comment]
Thanks for reporting this bug! I'll try to reproduce the bug and see how I can fix it
