### ISSUE TITLE
Cannot log in with Google account?

### ISSUE THREAD

**Issue by LucasCampbell0** [JustYuuto/deezer-discord-rpc#21]
Trying to log in, my Deezer account is linked to a google account but I can never get past the "Deezer wants additional access" screen. Just an endless loop of loading!

**Comment by WK-M** [comment]
Not exactly the same issue, but when trying to log in using a phone number, it will also endlessly loop as well.

**Comment by JustYuuto** [comment]
Hey, thanks for reporting this issue. I fixed it in https://github.com/JustYuuto/deezer-discord-rpc/commit/280737aa73cd9be2e3c7bc76a15060be52714108, just wait the next update

**Comment by LucasCampbell0** [comment]
It now says the browser isn't secure once you enter the email, weird..

**Comment by Korge** [comment]
same here
