### ISSUE TITLE
Need a update

### ISSUE THREAD

**Issue by Kisakay** [JustYuuto/deezer-discord-rpc#22]
With the new beautiful UI of Deezer, the method to grab titles, playing status, track name, album icons don't work anymore.

We need i think to change the method or anything else!

![image](https://github.com/JustYuuto/deezer-discord-rpc/assets/53227802/ed4e0abe-a131-4389-82c4-9c947243cce6)
You see? is very pretty <3

Cordially,
Anaïs

**Comment by Terryshield** [comment]
Hey, try to back version 1,18 for the moment, works for me.

**Comment by JustYuuto** [comment]
Hey, thanks for reporting this issue. I fixed it in https://github.com/JustYuuto/deezer-discord-rpc/commit/9515d348e5a649b08b368823d2442c2ff9f9a3b9, just wait for the next release
