### ISSUE TITLE
Straight up doesn't work

### ISSUE THREAD

**Issue by Clueeng** [JustYuuto/deezer-discord-rpc#24]
It doesn't show anything on the discord profile

**Comment by Haydenever** [comment]
it doesn't seem to work for me either, it only opens an app that looks exactly like Deezer but no one sees anything on Discord anyway :(

**Comment by DoggoNako** [comment]
Did you try restarting Deezer ? Did you also try to right click onto the app in the system tray click on "Reconnect to RPC", you can use websocket instead of RPC with "Use Listening to instead of Playing" but you need your Discord token.

**Comment by Haydenever** [comment]
oh right, I didn't quite get how it worked, but now it's all good! thank you!

**Comment by JustYuuto** [comment]
@Clueeng sorry for the inactivity, try this https://github.com/JustYuuto/deezer-discord-rpc/wiki/Troubleshooting#nothing-appears-on-my-profile

**Comment by danielzeljko** [comment]
If anyone is wondering how to get their discord token, you will need to:
1. Log in to the web version of discord
2. Open up your browser's dev tools
3. Click on the network tab
4. Search for `/api`
5. Within the results, search for `authorization` and copy the value
