### ISSUE TITLE
Adblock detected

### ISSUE THREAD

**Issue by flomirtech** [JustYuuto/deezer-discord-rpc#27]
Hey,

I don't understand why, on the Discord RPC application, I've had this window displayed ever since.
When I click on Adblock Disabled, it restarts the application and Discord visibility is no longer displayed.

However, I don't have Adblock.

![image](https://github.com/JustYuuto/deezer-discord-rpc/assets/65669857/13389389-668a-4bd8-a76c-5170a7c2204a)

Thank you for any indication,
Florent.

**Comment by flomirtech** [comment]
Resolved : DNS google.

**Comment by JustYuuto** [comment]
> However, I don't have Adblock.

I would like to note that there is an ad-blocker integrated into the app
