### ISSUE TITLE
Sometimes song titles dont but lengths get shown

### ISSUE THREAD

**Issue by ariebe9115** [JustYuuto/deezer-discord-rpc#3]
Sometimes when I listen to songs, the title just doesn't get shown, same for the length.
It just looks like this

![image](https://user-images.githubusercontent.com/64021242/232232082-361b45a7-8706-41df-8240-6b82637d8116.png)

The small image that is supposed to have the deezer logo doesn't show up entirely 

![image](https://user-images.githubusercontent.com/64021242/232232149-31d6ffd9-ef61-4778-a143-c621b3a6d6d8.png)

**Comment by ariebe9115** [comment]
I checked my status recently and since I updated to the latest version today, it happens quite frequently

**Comment by JustYuuto** [comment]
Thanks for reporting this bug! It happens sometimes for an unknown reason, I'll try to resolve it

**Comment by JustYuuto** [comment]
> The small image that is supposed to have the deezer logo doesn't show up entirely

Resolved in https://github.com/JustYuuto/deezer-discord-rpc/commit/1d0326cf27f0a35ca87a26eb8d0e528d5b1ec042
