### ISSUE TITLE
Suggestion : Add timer bar like Spotify Integration

### ISSUE THREAD

**Issue by Oceanraza** [JustYuuto/deezer-discord-rpc#37]
Add timer bar like Spotify Integration
![image](https://github.com/JustYuuto/deezer-discord-rpc/assets/147170631/508f1322-6510-4131-9ad8-3c4ffb2656af)

**Comment by JustYuuto** [comment]
As with the other issue, I can't due to Discord's limitations, which adds the time bar with Spotify only; on the other hand if you have Vencord you can use the [TimeBarAllActivities](https://vencord.dev/plugins/TimeBarAllActivities) plugin.
