### ISSUE TITLE
can't accept cookies/login

### ISSUE THREAD

**Issue by minimushii** [JustYuuto/deezer-discord-rpc#54]
I used to have discord rpc before I factory reset my laptop, and since then I haven't been able to make it past the opening screen because it's stuck on the 'accept cookies' tab because there is no accept or deny button. Am I doing something wrong?? 

![image](https://github.com/user-attachments/assets/1e00a88c-6dfb-489a-9e72-e3dae58da6fd)

**Comment by Mathu-lmn** [comment]
Yes same issue here

**Comment by Mathu-lmn** [comment]
Temp fix is to quit & relaunch, then be fast enough to click the connection you want before the cookies prompt appears

**Comment by unlolicon** [comment]
> Temp fix is to quit & relaunch, then be fast enough to click the connection you want before the cookies prompt appears
Same issue, temp fix doesnt work sadly since i dont have the login pre-filled and i dont want to link a google account to my deezer account

**Comment by minimushii** [comment]
yeah that's my issue too, and clicking the google thing just says it's already linked and its back to square one. thanks for the responses tho, guess we just have to wait for it to be fixed ig.

**Comment by Zalk0** [comment]
I'm kinda late but I just had the issue, you can open the developer tools with CTRL + SHIFT + I and in the HTML you go inside body and search the div with the id "cookie-banner-deezer" like so:
![image](https://github.com/user-attachments/assets/9a2532a7-cbac-4b4a-af8b-57ba2bff99fc)
You just have to right click on it and click on hide element.

**Comment by JustYuuto** [comment]
https://github.com/JustYuuto/deezer-discord-rpc/issues/61#issuecomment-2324709848
