### ISSUE TITLE
Rich presence does not shut down upon closing application

### ISSUE THREAD

**Issue by nazime1** [JustYuuto/deezer-discord-rpc#55]
I'm using the AppImage, so this might not be replicable on other versions, but on the AppImage version, after closing out of the application, rich presence still remains. In order to get rid of the rich presence I have to use System Monitor to end the rich presence process.
Not sure if this has to do with it too but the tray icon is gone as of 1.2.6, so I can't close rich presence that way. Here's the rich presence running with no tray icon.

![image](https://github.com/user-attachments/assets/24257e0f-47bd-4c39-9374-ce070b530b9b)

My Discord rich presence after closing the application:

![image](https://github.com/user-attachments/assets/4ac9c396-d6c5-4892-ae58-967ee4eb20ca)

**Comment by JustYuuto** [comment]
Fixed in the latest update :)
