### ISSUE TITLE
`Use "Listening to" instead of "Playing"` doesn't seem to detect my token

### ISSUE THREAD

**Issue by jinetty** [JustYuuto/deezer-discord-rpc#6]
I pasted my discord user token but it seems it cannot take my token.

```
[Protocol] Registered protocol
[App] Deezer Discord RPC version 1.1.11 
[119178:0424/004325.506192:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[Updater] Checking for updates...
[Updater] No updates found.
[WebSocket] Connected to Discord WebSocket server
[WebSocket] Sent authentication payload
[Menu] Updating menu entries...
[Menu] Updated menu entries
[Menu] Updating menu entries...
[Menu] Updated menu entries
[119178:0424/004331.303033:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[119178:0424/004331.304314:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
[Activity] Updating because music got changed
[Spotify Covers] Access token expired; refreshing it
(node:119124) UnhandledPromiseRejectionWarning: AxiosError: Request failed with status code 400
(Use `deezer-discord-rpc --trace-warnings ...` to show where the warning was created)
(node:119124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
[Activity] Updating because music got changed
[Spotify Covers] Access token expired; refreshing it
(node:119124) UnhandledPromiseRejectionWarning: AxiosError: Request failed with status code 400
(node:119124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
[Activity] Updating because music got changed
```
Am I pasting wrong token ?

**Comment by jinetty** [comment]
I figured app did not save my token into `$HOME/.config/deezer-discord-rpc/config.json` so i put `spotify_access_token` and `spotify_token_type` myself into config file.
```
{
    "spotify_access_token":"SPOTIFY_TOKEN",
    "spotify_token_type": "Bearer",
    "discord_token":"DISCORD_TOKEN",
    "use_listening_to":true,
    "only_show_if_playing":true
}
```
from https://accounts.spotify.com/authorize?response_type=token&client_id=client_id&redirect_uri=redirect_uri_of_application&grant_type=refresh_token link.

**Comment by JustYuuto** [comment]
You (normally) don't need to do it manually, you sure that you clicked the circled link on the screenshot and authorized your Spotify account?

![Screenshot 2023-05-01 at 18 25 51](https://user-images.githubusercontent.com/55290516/235542602-a33b52c9-d5b9-4c5d-a7bd-700550217b72.png)

**Comment by jinetty** [comment]
I did it actually but it didn't wrote token into my config file.

**Comment by jinetty** [comment]
![image](https://user-images.githubusercontent.com/64617882/235800591-4760487b-ef91-4b9c-a05b-dd024d0e4090.png)
This error is from spawning new window, it wasn't happening before merged your new commits.

**Comment by JustYuuto** [comment]
Hi! Sorry for not having answered your comment, when you installed the app did you take the `.AppImage` file or the `.snap` file?

**Comment by Chroni69** [comment]
Hi, just encountered the same bug. After pasting the token without Spotify Login it just doesnt work. With the Spotify (Free) Login it works, so there's obviously a dependance.

**Comment by NocFA** [comment]
I noticed the above, too with regards to Spotify seemingly being non-negotiable, which, is funny considering using the Spotify feature for cover art appears to not function at all, although, that's a topic for another issue.

**Comment by JustYuuto** [comment]
> It's also not displaying the remaining time of the title, but i guess that's just a technical limitation.

On PC it's not, but on phone it's showing. Idk why Discord does this, but I can't change anything about this.
