### ISSUE TITLE
AD-BLOCK Problem

### ISSUE THREAD

**Issue by ChristopherCapuozzo** [JustYuuto/deezer-discord-rpc#62]
Impossible to play music, otherwise you have to click on play randomly and then you can click on our music

![image](https://github.com/user-attachments/assets/ee10bf7d-77a8-4590-91ec-cb0e89d36c63)

**Comment by JustYuuto** [comment]
Hi, do you still have the problem?

**Comment by ChristopherCapuozzo** [comment]
With 1.3.0 no, but I'll keep you informed if the problem comes back

**Comment by JustYuuto** [comment]
Nice to hear, I'll close the issue as you no longer have the issue but feel free to keep me updated if the problem reoccurs!
