### ISSUE TITLE
Deezer RPC currently working as the regular app

### ISSUE THREAD

**Issue by Umagarm** [JustYuuto/deezer-discord-rpc#63]
Version 1.2.7 had been working normally until recently, but now neither the "Playing" nor the "Listening" status are shown on Discord. The new Forward and Back arrows have also disappeared (excellent addition btw! <3), and the app doesn't close to tray regardless of the tray settings (closing it just terminates the program).

I've tried restarting my PC and performing a clean install of the app to no avail. It basically functions the same as the stock app.

Thank you as always!

**Comment by LittleNoises** [comment]
Yeah, I have the same problem, but at least the ad blocker still works haha.

**Comment by JustYuuto** [comment]
Normally it has been fixed in the latest update :)
