### ISSUE TITLE
Deezer RPC not displaying songs

### ISSUE THREAD

**Issue by 8errad** [JustYuuto/deezer-discord-rpc#64]
When i use the app the song is not displaying only deezer and playiing since ..... time !

And it's been like this since 1.2.6 and it's still bugged after 1.2.7 update 

Thank you though for everything i really hope you can help me !

![DISCORD](https://github.com/user-attachments/assets/ec8ccfd6-b211-4539-8ef6-f4291f1589d0)

**Comment by JustYuuto** [comment]
#65
