### ISSUE TITLE
Song not display on Discord

### ISSUE THREAD

**Issue by BlocBlocTheDev** [JustYuuto/deezer-discord-rpc#65]
When we listen a music, discord don't display on the profile : 

![image](https://github.com/user-attachments/assets/17158195-d3e0-4627-8e84-ff25cba83392)

![image](https://github.com/user-attachments/assets/c6c704f9-ced1-4b06-93be-2f43876bd21f)

Same problem in "Playing" mod and "Listening" mod

Sorry for english, i'm a French guy... :/

**Comment by JustYuuto** [comment]
Je suis français aussi :)

Essaye avec ça : https://github.com/JustYuuto/deezer-discord-rpc/wiki/Troubleshooting

**Comment by BlocBlocTheDev** [comment]
Re !

Malheureusement le problème persiste, même après avoir tenter de suivre les consigne de débugage...

Et quelque soit le mode utilisé rien n'apparait.

Le problème est apparu de mon coté après la dernière mise à jour (1.2.7)

J'ai tenté d'utiliser le RPC avec une autre application et ça marche donc il doit y avoir un souci avec la dernière MAJ :/

J'ai essayé de fournir le plus de détails possible en espérant que cela puisse aider !

**Comment by BlocBlocTheDev** [comment]
EDIT : Même en revenant sur la version précédente le problème est toujours présent.

**Comment by JustYuuto** [comment]
Ah sorry je vais voir ça quand j'ai le temps et puis je ferais une update, merci du retour en tous cas

**Comment by BlocBlocTheDev** [comment]
Pas de souci !

Ma piste c'est que Discord à changé un truc qui fait que l'application n'arrive plus à update le RPC.
Mais bon vu que je connais rien à JS ou Discord je préfère pas trop m'avancer dessus.

Bon courage !

**Comment by kylianrcd** [comment]
La même, je pense que ça vient aussi de discord pour que ça arrête de marcher comme ça du jour au lendemain

**Comment by flomirtech** [comment]
Bonjour, je confirme également le problème sur la version actuelle et la précédente. Discord a dû changer une fonction lié au RPC avec Deezer 😅

**Comment by TanukiPenny** [comment]
Sorry to come in with English here lol, but I think Deezer changed something about their website that caused some of the mods that this program does to fail and break. That's why old versions do not work either cause they use the same website from Deezer. I just submitted PR #66 that should fix this!

**Comment by kylianrcd** [comment]
> Sorry to come in with English here lol, but I think Deezer changed something about their website that caused some of the mods that this program does to fail and break. That's why old versions do not work either cause they use the same website from Deezer. I just submitted PR #66 that should fix this!

Can we test it ourselves by compiling the code?

**Comment by TanukiPenny** [comment]
Yes, if you pull my fork and build it you can test it

**Comment by flomirtech** [comment]
> Yes, if you pull my fork and build it you can test it

How do you transform your fork into an .exe file ?

**Comment by kylianrcd** [comment]
> Yes, if you pull my fork and build it you can test it

![2024-08-18 20_05_19-Window](https://github.com/user-attachments/assets/5b366e70-59d5-47b6-beb0-7daef43731d4)
Work guys gg you can use the pull

**Comment by kylianrcd** [comment]
I've managed to compile the application incorporating the pull request modifications. Here's an overview of the process:

1. I applied the pull request changes manually in my local repository clone.

2. I had to make several additional adjustments, notably in the `package.json` file and potentially in other configuration files.

3. Next, I followed a compilation process similar to this one:

   - Installation of dependencies: `npm install`
   - TypeScript compilation: `npm run build:ts`
   - Executable creation: `npm run build:electron`

4. The final executable is located in the `dist` folder.

It's important to note that the process required a few specific adaptations, not all of which are detailed here. If you'd like to reproduce exactly what I've done, I can provide more detailed instructions on the modifications made.

> > Yes, if you pull my fork and build it you can test it
> 
> How do you transform your fork into an .exe file ?

I've managed to compile the application incorporating the pull request modifications. Here's an overview of the process:

1. I applied the pull request changes manually in my local repository clone.

2. I had to make several additional adjustments, notably in the `package.json` file and potentially in other configuration files.

3. Next, I followed a compilation process similar to this one:

   - Installation of dependencies: `npm install`
   - TypeScript compilation: `npm run build:ts`
   - Executable creation: `npm run build:electron`

4. The final executable is located in the `dist` folder.

It's important to note that the process required a few specific adaptations, not all of which are detailed here. If you'd like to reproduce exactly what I've done, I can provide more detailed instructions on the modifications made.

**Comment by TanukiPenny** [comment]
Pretty sure it's just 'yarn install' then 'yarn build'. You should not have to modify anything except that changes I made in the or

**Comment by JuSteFat** [comment]
> Pretty sure it's just 'yarn install' then 'yarn build'. Once the yarn build runs then the installer should be in a dist folder or a build folder. You should not have to modify anything except the changes I made in the pr

Yes, but as I'd never compiled before, I followed claude-3.5's advice to use electron and make a portable version of deezer RPC. By the time it worked, I was happy.

**Comment by BlocBlocTheDev** [comment]
GG guys, now wait for a release in this repo :)
🍾🍾🍾

**Comment by JuSteFat** [comment]
> GG guys, now wait for a release in this repo :) 🍾🍾🍾

I just make a fork with the pull if you want : https://github.com/JuSteFat/deezer-discord-rpc/releases/tag/deezer

**Comment by flomirtech** [comment]
![image](https://github.com/user-attachments/assets/adb7b9be-2d57-434f-a8c5-52684a79d93c)
Good Job @TanukiPenny & @JuSteFat.
It works perfercly !
Thanks you very much 🍾

**Comment by JustYuuto** [comment]
Hi there, sorry for my inactivity here :(

Thank you @TanukiPenny and @JuSteFat for your help 😅, anyway I released another version that fixes some fixes :) 

I'll leave this issue open in case anyone has the issue even with the latest update
