### ISSUE TITLE
"'Listening to' instead of 'Playing'" causes websocket connection error

### ISSUE THREAD

**Issue by QueenOfRodents** [JustYuuto/deezer-discord-rpc#7]
Hello,

I've been getting this error whenever I use the "Listening to" instead of "Playing" option and using my discord token + spotify token. I have been copying my token from the correct place (assumedly) and leaving out none of it, so I assume it is an issue on the side of the application. The application takes my token as valid, but repeatedly gives me this error and does not give me the Playing status.

I appreciate any help, even if it is pointing out that I may be a bit stupid.

![errorooror](https://github.com/JustYuuto/deezer-discord-rpc/assets/88874490/73167c86-aae7-48a9-9237-35ec4601dcbf)

**Comment by JustYuuto** [comment]
Hi, thanks for reporting the issue! I'll try to reproduce it and see how can I resolve it

**Comment by JustYuuto** [comment]
fixed in https://github.com/JustYuuto/deezer-discord-rpc/commit/a124fb5fb07e9928ff9c53a974ea28bf7d91223b! I'll release a new update in 15 mins
