### ISSUE TITLE
Doesnt show on profile anymore since 1.2.8

### ISSUE THREAD

**Issue by Tryphamour** [JustYuuto/deezer-discord-rpc#70]
Just updated deezer discord rpc to the new 1.2.8 version, and since then, it doesn't show anything on my discord profile anymore (it was working great before, I was even using the "Listen to" mode with the discord token).
I tried to quit both apps and relaunch them, also tried to play a little bit with the rpc options to see if I can make it work by any chance but nothing worked for me, any idea ? Thanks

**Comment by hans-juergen** [comment]
Same for me, just installed your app version 1..28 for the first time and do not see anything on Discord while playing an album on Deezer.

**Comment by hans-juergen** [comment]
Does this app only work with the Discord desktop app and not with their web UI perhaps? I checked the Troubleshooting wiki which showed this necessary option in a screenshot: "Check the "Display current activity as a status message" option". I don't have this option in the web UI of Discord, I only see these options:
![image](https://github.com/user-attachments/assets/16998136-0893-4623-99f7-9aa14492763e)
So maybe displaying my current activity as a status message is only available in the Discord desktop app?

**Comment by JustYuuto** [comment]
Hi! Deezer may have changed things in their code that broke the RPC, the latest version should fix this! https://github.com/JustYuuto/deezer-discord-rpc/releases/tag/1.3.0

**Comment by Tryphamour** [comment]
Indeed, it works again since a few weeks and forgot to update my comment here. Thank's for your work, great app :)
