### ISSUE TITLE
Install.md

### ISSUE THREAD

**Issue by bdols** [JustYuuto/deezer-discord-rpc#77]
I'm not an "electron guy", much less a "nodejs-guy", yet I was intrigued enough to try this application out based on a post here: https://en.deezercommunity.com/ideas/deezer%2Ddiscord%2Drich%2Dpresence%2D7434/index6.html

I run deezer inside flatpak. I run vesktop in flatpak too with the arRPC plugin, and I can get games detected and advertised.

It's unclear how to install deezer-discord-rpc.
I've made progress with "nix-shell -p yarn" and flailing with some yarn commands managed to get a deezer thing running, but then it wasn't clear that the RPC portion was working at all. I also see errors like this on the console:
(node:2737359) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 24)

**Comment by JustYuuto** [comment]
Hi, which OS are you on?

**Comment by bdols** [comment]
> Hi, which OS are you on?

I am running the bluefin variant of Fedora's Silverblue

**Comment by JustYuuto** [comment]
> I am running the bluefin variant of Fedora's Silverblue
The latest release includes a rpm file, but I don't know if it'll work

**Comment by bdols** [comment]
I ran the AppImage and it works!

**Comment by JustYuuto** [comment]
> I ran the AppImage and it works!

Nice :)
