### ISSUE TITLE
Covers doesn't work on Listening Mode

### ISSUE THREAD

**Issue by DvoraNoob** [JustYuuto/deezer-discord-rpc#8]
The album covers isn't work more on Listening Mode

**Comment by JustYuuto** [comment]
I can't explain it better 
![image](https://github.com/JustYuuto/deezer-discord-rpc/assets/55290516/46c08d91-7f77-4ae7-96fe-cfbf2df75a89)

**Comment by DvoraNoob** [comment]
> I can't explain it better ![image](https://user-images.githubusercontent.com/55290516/251230649-46c08d91-7f77-4ae7-96fe-cfbf2df75a89.png)

So I linked my Spotify account, before this last update sometimes the covers worked and sometimes not, but now not even the default image shows anymore

**Comment by JustYuuto** [comment]
> So I linked my Spotify account, before this last update sometimes the covers worked and sometimes not, but now not even the default image shows anymore

The default image was the small image that I removed, and sometimes the cover is not showing because of Spotify
