### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by gekkenaam123** [JustYuuto/deezer-discord-rpc#83]
Unlike the normal deezer application this one does not have navigation buttons at the top of the screen. this is really annoying because you can't go back to the previous page. for example if you are looking at albums by an artist, there is no way to go back to the previous page, so everytime you want to look at a different song or album you have to search the name of the artist over and over again.

**Comment by JustYuuto** [comment]
Hi, it should be fixed in the latest release :) https://github.com/JustYuuto/deezer-discord-rpc/releases/tag/1.3.0

**Comment by gekkenaam123** [comment]
hi, i just updated to the new version, but there is still no naviation buttons. also, my music haven't been showing on discord for a while now, even after updating to the newest version.

**Comment by JustYuuto** [comment]
try uninstalling the reinstalling the app, this is weird

**Comment by gekkenaam123** [comment]
i already tried that twice. also my music isn't showing on discord for a while now, even after the update. today it worked for the first time in 3 weeks, but it stopt working after i restarted the app

**Comment by gekkenaam123** [comment]
i accidentally found the issue. for some reason if i have battery saver turned on in windows, the rpc does not work, but as soon as i turn it of and then restart the app my music finally shows on discord. as soon as i turn on windows batery saver it immediately stops working tho.

**Comment by JustYuuto** [comment]
Well I didn't know Windows battery saver could cause this.
